name: 每日新闻推送
on:
  schedule:
    # cron是UTC时区！ 0 8 * * * = UTC早上8点 = 北京时间16点
    - cron: "0 8 * * *"
  # 允许网页手动运行测试
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖requests
        run: pip install requests

      - name: 执行新闻脚本
        env:
          ALAPI_TOKEN: ${{ secrets.ALAPI_TOKEN }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python main.py
