name: 每日热点新闻推送
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖requests
        run: pip install requests

      - name: 执行新闻推送脚本
        env:
          ALAPI_TOKEN: ${{ secrets.ALAPI_TOKEN }}
          WX_APPID: ${{ secrets.WX_APPID }}
          WX_APPSECRET: ${{ secrets.WX_APPSECRET }}
          WX_OPENID: ${{ secrets.WX_OPENID }}
          WX_TEMPLATE_ID: ${{ secrets.WX_TEMPLATE_ID }}
          # 下面这一行就是你缺失的！！
          ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
        run: python main.py
